export default {
  GET_GROUP_REQUEST: 'GET_GROUP_REQUEST',
  GET_GROUP_SUCCESS: 'GET_GROUP_SUCCESS',
  GET_GROUP_FAILURE: 'GET_GROUP_FAILURE',

  GET_GROUP_DETAILS_REQUEST: 'GET_GROUP_DETAILS_REQUEST',
  GET_GROUP_DETAILS_SUCCESS: 'GET_GROUP_DETAILS_SUCCESS',
  GET_GROUP_DETAILS_FAILURE: 'GET_GROUP_DETAILS_FAILURE',
};
