export const GET_SHIFTS_REQUEST = 'GET_SHIFTS_REQUEST';
export const GET_SHIFTS_SUCCESS = 'GET_SHIFTS_SUCCESS';
export const GET_SHIFTS_FAILURE = 'GET_SHIFTS_FAILURE';

export const GET_SHIFT_DETAIL_REQUEST = 'GET_SHIFT_DETAIL_REQUEST';
export const GET_SHIFT_DETAIL_SUCCESS = 'GET_SHIFT_DETAIL_SUCCESS';
export const GET_SHIFT_DETAIL_FAILURE = 'GET_SHIFT_DETAIL_FAILURE';
