export default {
  MEAL_STATISTIC_FILTER: 'MEAL_STATISTIC_FILTER',

  GET_MEAL_STATISTIC_REQUEST: 'GET_MEAL_STATISTIC_REQUEST',
  GET_MEAL_STATISTIC_SUCCESS: 'GET_MEAL_STATISTIC_SUCCESS',
  GET_MEAL_STATISTIC_FAILURE: 'GET_MEAL_STATISTIC_FAILURE',

  GET_LIST_EMPLOYEE_POST_BY_LEADER_REQUEST: 'GET_LIST_EMPLOYEE_POST_BY_LEADER_REQUEST',
  GET_LIST_EMPLOYEE_POST_BY_LEADER_SUCCESS: 'GET_LIST_EMPLOYEE_POST_BY_LEADER_SUCCESS',
  GET_LIST_EMPLOYEE_POST_BY_LEADER_FAILURE: 'GET_LIST_EMPLOYEE_POST_BY_LEADER_FAILURE',

  GET_RICE_REGISTERED_OF_EMPLOYEE_REQUEST: 'GET_RICE_REGISTERED_OF_EMPLOYEE_REQUEST',
  GET_RICE_REGISTERED_OF_EMPLOYEE_SUCCESS: 'GET_RICE_REGISTERED_OF_EMPLOYEE_SUCCESS',
  GET_RICE_REGISTERED_OF_EMPLOYEE_FAILURE: 'GET_RICE_REGISTERED_OF_EMPLOYEE_FAILURE',

  GET_TYPE_REGISTERED_MEAL_REQUEST: 'GET_TYPE_REGISTERED_MEAL_REQUEST',
  GET_TYPE_REGISTERED_MEAL_SUCCESS: 'GET_TYPE_REGISTERED_MEAL_SUCCESS',
  GET_TYPE_REGISTERED_MEAL_FAILURE: 'GET_TYPE_REGISTERED_MEAL_FAILURE',

  UPDATE_MEAL_TYPE_REQUEST: 'UPDATE_MEAL_TYPE_REQUEST',
  UPDATE_MEAL_TYPE_SUCCESS: 'UPDATE_MEAL_TYPE_SUCCESS',
  UPDATE_MEAL_TYPE_FAILURE: 'UPDATE_MEAL_TYPE_FAILURE',

  CONFIRM_REGISTERED_MEAL_REQUEST: 'CONFIRM_REGISTERED_MEAL_REQUEST',
  CONFIRM_REGISTERED_MEAL_SUCCESS: 'CONFIRM_REGISTERED_MEAL_SUCCESS',
  CONFIRM_REGISTERED_MEAL_FAILURE: 'CONFIRM_REGISTERED_MEAL_FAILURE',
};
