export default {

  GET_TEMPERATURE_REQUEST: 'GET_TEMPERATURE_REQUEST',
  GET_TEMPERATURE_SUCCESS: 'GET_TEMPERATURE_SUCCESS',
  GET_TEMPERATURE_FAILURE: 'GET_TEMPERATURE_FAILURE',

  UPDATE_TEMPERATURE_REQUEST: 'UPDATE_TEMPERATURE_REQUEST',
  UPDATE_TEMPERATURE_SUCCESS: 'UPDATE_TEMPERATURE_SUCCESS',
  UPDATE_TEMPERATURE_FAILURE: 'UPDATE_TEMPERATURE_FAILURE',

};
