export default {
  GET_LEVEL_ONE_BY_CONTACT_REQUEST:
    'GET_LEVEL_ONE_BY_CONTACT_REQUEST',
  GET_LEVEL_ONE_BY_CONTACT_SUCCESS:
    'GET_LEVEL_ONE_BY_CONTACT_SUCCESS',
  GET_LEVEL_ONE_BY_CONTACT_FAILURE:
    'GET_LEVEL_ONE_BY_CONTACT_FAILURE',

  GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_FAILURE: 'GET_CONTACTS_FAILURE',

  GET_CONTACT_GROUP_REQUEST: 'GET_CONTACT_GROUP_REQUEST',
  GET_CONTACT_GROUP_SUCCESS: 'GET_CONTACT_GROUP_SUCCESS',
  GET_CONTACT_GROUP_FAILURE: 'GET_CONTACT_GROUP_FAILURE',

  CREATE_CONTACT_REQUEST: 'CREATE_CONTACT_REQUEST',
  CREATE_CONTACT_SUCCESS: 'CREATE_CONTACT_SUCCESS',
  CREATE_CONTACT_FAILURE: 'CREATE_CONTACT_FAILURE',

  UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
  UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_FAILURE: 'UPDATE_CONTACT_FAILURE',

  DELETE_CONTACT_REQUEST: 'DELETE_CONTACT_REQUEST',
  DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
  DELETE_CONTACT_FAILURE: 'DELETE_CONTACT_FAILURE',
};
