export default {
  GET_LEVEL_ONE_BY_UNIT_REQUEST:
    'GET_LEVEL_ONE_BY_UNIT_REQUEST',
  GET_LEVEL_ONE_BY_UNIT_SUCCESS:
    'GET_LEVEL_ONE_BY_UNIT_SUCCESS',
  GET_LEVEL_ONE_BY_UNIT_FAILURE:
    'GET_LEVEL_ONE_BY_UNIT_FAILURE',

  GET_LEVEL_TWO_BY_UNIT_REQUEST:
    'GET_LEVEL_TWO_BY_UNIT_REQUEST',
  GET_LEVEL_TWO_BY_UNIT_SUCCESS:
    'GET_LEVEL_TWO_BY_UNIT_SUCCESS',
  GET_LEVEL_TWO_BY_UNIT_FAILURE:
    'GET_LEVEL_TWO_BY_UNIT_FAILURE',

  GET_LEVEL_THREE_BY_UNIT_REQUEST:
    'GET_LEVEL_THREE_BY_UNIT_REQUEST',
  GET_LEVEL_THREE_BY_UNIT_SUCCESS:
    'GET_LEVEL_THREE_BY_UNIT_SUCCESS',
  GET_LEVEL_THREE_BY_UNIT_FAILURE:
    'GET_LEVEL_THREE_BY_UNIT_FAILURE',

  GET_LEVEL_FOUR_BY_UNIT_REQUEST:
    'GET_LEVEL_FOUR_BY_UNIT_REQUEST',
  GET_LEVEL_FOUR_BY_UNIT_SUCCESS:
    'GET_LEVEL_FOUR_BY_UNIT_SUCCESS',
  GET_LEVEL_FOUR_BY_UNIT_FAILURE:
    'GET_LEVEL_FOUR_BY_UNIT_FAILURE',

  GET_UNITS_REQUEST: 'GET_UNITS_REQUEST',
  GET_UNITS_SUCCESS: 'GET_UNITS_SUCCESS',
  GET_UNITS_FAILURE: 'GET_UNITS_FAILURE',

  GET_UNIT_GROUP_REQUEST: 'GET_UNIT_GROUP_REQUEST',
  GET_UNIT_GROUP_SUCCESS: 'GET_UNIT_GROUP_SUCCESS',
  GET_UNIT_GROUP_FAILURE: 'GET_UNIT_GROUP_FAILURE',

  CREATE_UNIT_REQUEST: 'CREATE_UNIT_REQUEST',
  CREATE_UNIT_SUCCESS: 'CREATE_UNIT_SUCCESS',
  CREATE_UNIT_FAILURE: 'CREATE_UNIT_FAILURE',

  UPDATE_UNIT_REQUEST: 'UPDATE_UNIT_REQUEST',
  UPDATE_UNIT_SUCCESS: 'UPDATE_UNIT_SUCCESS',
  UPDATE_UNIT_FAILURE: 'UPDATE_UNIT_FAILURE',

  DELETE_UNIT_REQUEST: 'DELETE_UNIT_REQUEST',
  DELETE_UNIT_SUCCESS: 'DELETE_UNIT_SUCCESS',
  DELETE_UNIT_FAILURE: 'DELETE_UNIT_FAILURE',
};
