export default {
  KPI_FILTER: 'KPI_FILTER',
  KPI_DETAIL_FILTER: 'KPI_DETAIL_FILTER',

  GET_KPI_DETAIL_REQUEST: 'GET_KPI_DETAIL_REQUEST',
  GET_KPI_DETAIL_SUCCESS: 'GET_KPI_DETAIL_SUCCESS',
  GET_KPI_DETAIL_FAILURE: 'GET_KPI_DETAIL_FAILURE',
};
