export default {
  GET_SCHEDULE_GROUP_REQUEST: 'GET_SCHEDULE_GROUP_REQUEST',
  GET_SCHEDULE_GROUP_SUCCESS: 'GET_SCHEDULE_GROUP_SUCCESS',
  GET_SCHEDULE_GROUP_FAILURE: 'GET_SCHEDULE_GROUP_FAILURE',
};
