export default {
  ABSENT_STATISTIC_FILTER: 'ABSENT_STATISTIC_FILTER',
  GET_ABSENT_STATISTIC_REQUEST: 'GET_ABSENT_STATISTIC_REQUEST',
  GET_ABSENT_STATISTIC_SUCCESS: 'GET_ABSENT_STATISTIC_SUCCESS',
  GET_ABSENT_STATISTIC_FAILURE: 'GET_ABSENT_STATISTIC_FAILURE',
};
