export default {
  SET_OVER_BODY_TEMPERATURE_FILTER: 'SET_OVER_BODY_TEMPERATURE_FILTER',
  GET_OVER_BODY_TEMPERATURES_REQUEST: 'GET_OVER_BODY_TEMPERATURES_REQUEST',
  GET_OVER_BODY_TEMPERATURES_SUCCESS: 'GET_OVER_BODY_TEMPERATURES_SUCCESS',
  GET_OVER_BODY_TEMPERATURES_FAILURE: 'GET_OVER_BODY_TEMPERATURES_FAILURE',
};
