export default {

  GET_TIME_OFF_TYPE_REQUEST: 'GET_TIME_OFF_TYPE_REQUEST',
  GET_TIME_OFF_TYPE_SUCCESS: 'GET_TIME_OFF_TYPE_SUCCESS',
  GET_TIME_OFF_TYPE_FAILURE: 'GET_TIME_OFF_TYPE_FAILURE',

  UPDATE_TIME_OFF_TYPE_REQUEST: 'UPDATE_TIME_OFF_TYPE_REQUEST',
  UPDATE_TIME_OFF_TYPE_SUCCESS: 'UPDATE_TIME_OFF_TYPE_SUCCESS',
  UPDATE_TIME_OFF_TYPE_FAILURE: 'UPDATE_TIME_OFF_TYPE_FAILURE',

};
