export const SCHEDULE_FILTER = 'SCHEDULE_FILTER';

export const GET_SCHEDULES_REQUEST = 'GET_SCHEDULES_REQUEST';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAILURE = 'GET_SCHEDULES_FAILURE';

export const GET_SCHEDULES_OF_EMPLOYEE_REQUEST = 'GET_SCHEDULES_OF_EMPLOYEE_REQUEST';
export const GET_SCHEDULES_OF_EMPLOYEE_SUCCESS = 'GET_SCHEDULES_OF_EMPLOYEE_SUCCESS';
export const GET_SCHEDULES_OF_EMPLOYEE_FAILURE = 'GET_SCHEDULES_OF_EMPLOYEE_FAILURE';


