export default {
  SET_EMPLOYEE_FILTER: 'SET_EMPLOYEE_FILTER',
  CONTRACT_DETAILS_SELECTED: 'CONTRACT_DETAILS_SELECTED',

  GET_EMPLOYEES_REQUEST: 'GET_EMPLOYEES_REQUEST',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEES_FAILURE: 'GET_EMPLOYEES_FAILURE',
  
  GET_EMPLOYEE_DETAILS_REQUEST: 'GET_EMPLOYEE_DETAILS_REQUEST',
  GET_EMPLOYEE_DETAILS_SUCCESS: 'GET_EMPLOYEE_DETAILS_SUCCESS',
  GET_EMPLOYEE_DETAILS_FAILURE: 'GET_EMPLOYEES_DETAILS_FAILURE',
}