export default {
  ATTENDANCE_FILTER: 'ATTENDANCE_FILTER',
  ATTENDANCE_HISTORY_FILTER: 'ATTENDANCE_HISTORY_FILTER',
  ATTENDANCE_DETAIL_FILTER: 'ATTENDANCE_DETAIL_FILTER',

  GET_ATTENDANCES_REQUEST: 'GET_ATTENDANCES_REQUEST',
  GET_ATTENDANCES_SUCCESS: 'GET_ATTENDANCES_SUCCESS',
  GET_ATTENDANCES_FAILURE: 'GET_ATTENDANCES_FAILURE',

  GET_ATTENDANCE_BY_EMPLOYEE_REQUEST: 'GET_ATTENDANCE_BY_EMPLOYEE_REQUEST',
  GET_ATTENDANCE_BY_EMPLOYEE_SUCCESS: 'GET_ATTENDANCE_BY_EMPLOYEE_SUCCESS',
  GET_ATTENDANCE_BY_EMPLOYEE_FAILURE: 'GET_ATTENDANCE_BY_EMPLOYEE_FAILURE',

  GET_ATTENDANCE_HISTORY_REQUEST: 'GET_ATTENDANCE_HISTORY_REQUEST',
  GET_ATTENDANCE_HISTORY_SUCCESS: 'GET_ATTENDANCE_HISTORY_SUCCESS',
  GET_ATTENDANCE_HISTORY_FAILURE: 'GET_ATTENDANCE_HISTORY_FAILURE',

  GET_ATTENDANCE_ANALYSIS_BY_DAY_REQUEST: 'GET_ATTENDANCE_ANALYSIS_BY_DAY_REQUEST',
  GET_ATTENDANCE_ANALYSIS_BY_DAY_SUCCESS: 'GET_ATTENDANCE_ANALYSIS_BY_DAY_SUCCESS',
  GET_ATTENDANCE_ANALYSIS_BY_DAY_FAILURE: 'GET_ATTENDANCE_ANALYSIS_BY_DAY_FAILURE',

  GET_ATTENDANCE_ANALYSIS_BY_WEEK_REQUEST: 'GET_ATTENDANCE_ANALYSIS_BY_WEEK_REQUEST',
  GET_ATTENDANCE_ANALYSIS_BY_WEEK_SUCCESS: 'GET_ATTENDANCE_ANALYSIS_BY_WEEK_SUCCESS',
  GET_ATTENDANCE_ANALYSIS_BY_WEEK_FAILURE: 'GET_ATTENDANCE_ANALYSIS_BY_WEEK_FAILURE',

  GET_ATTENDANCE_REASON_REQUEST: 'GET_ATTENDANCE_REASON_REQUEST',
  GET_ATTENDANCE_REASON_SUCCESS: 'GET_ATTENDANCE_REASON_SUCCESS',
  GET_ATTENDANCE_REASON_FAILURE: 'GET_ATTENDANCE_REASON_FAILURE',

  SELECTED_ATTENDANCE: 'SELECTED_ATTENDANCE',
};
