export default {
  GET_PERMISSION_REQUEST: 'GET_PERMISSION_REQUEST',
  GET_PERMISSION_SUCCESS: 'GET_PERMISSION_SUCCESS',
  GET_PERMISSION_FAILURE: 'GET_PERMISSION_FAILURE',

  GET_PERMISSION_DETAILS_REQUEST: 'GET_PERMISSION_DETAILS_REQUEST',
  GET_PERMISSION_DETAILS_SUCCESS: 'GET_PERMISSION_DETAILS_SUCCESS',
  GET_PERMISSION_DETAILS_FAILURE: 'GET_PERMISSION_DETAILS_FAILURE',
};
