export default {
  GET_ROLE_REQUEST: 'GET_ROLE_REQUEST',
  GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
  GET_ROLE_FAILURE: 'GET_ROLE_FAILURE',

  GET_ROLE_DETAILS_REQUEST: 'GET_ROLE_DETAILS_REQUEST',
  GET_ROLE_DETAILS_SUCCESS: 'GET_ROLE_DETAILS_SUCCESS',
  GET_ROLE_DETAILS_FAILURE: 'GET_ROLE_DETAILS_FAILURE',

  GET_ROLE_PERMISSION_REQUEST: 'GET_ROLE_PERMISSION_REQUEST',
  GET_ROLE_PERMISSION_SUCCESS: 'GET_ROLE_PERMISSION_SUCCESS',
  GET_ROLE_PERMISSION_FAILURE: 'GET_ROLE_PERMISSION_FAILURE',
};
